### ISSUE TITLE
Make results in a missing file error

### ISSUE THREAD

**Issue by syusuf1234** [embedefy/pgembedefy#4]
`api.c:5:10: fatal error: 'json-c/json.h' file not found`

**Comment by devfacet** [comment]
Hi, you need [json-c](https://github.com/json-c/json-c) library on your system. On Ubuntu you can install it via "apt-get update && apt-get install libjson-c-dev"

P.S. See Ubuntu and Dockerfile examples at https://www.embedefy.com/docs/pgembedefy

**Comment by syusuf1234** [comment]
thank you, had to install through homebrew on MacOS and then MAKE succeeded with a variant like below 

`make LDFLAGS=-L/path/to/json-c/lib LIBS=-ljson-c`
